// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Load .env.local first (higher priority), then .env
config({ path: ".env.local", override: true });
config({ path: ".env", override: false });

// For Prisma Postgres with Accelerate:
// - DATABASE_URL: Direct database connection (for migrations)
// - PRISMA_DATABASE_URL: Accelerate pooled connection (for queries)
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"), // Use direct connection for migrations
  },
});
