export type BlogPost = {
  slug: string;
  title: Record<"en" | "lt", string>;
  summary: Record<"en" | "lt", string>;
  date: string;
  readingTime: Record<"en" | "lt", string>;
  tags: Record<"en" | "lt", string[]>;
  content: Record<"en" | "lt", string[]>;
};

export const blogPosts: BlogPost[] = [
  {
    slug: "content-structure-beats-beautiful-design",
    title: {
      en: "Content Structure Beats Beautiful Design Every Time",
      lt: "Turinio struktūra visada įveikia gražų dizainą",
    },
    summary: {
      en: "A well-structured page with basic design converts better than a beautiful page with poor structure. Here's how to get it right.",
      lt: "Gerai struktūruotas puslapis su pagrindiniu dizainu konvertuoja geriau nei gražus puslapis su prasta struktūra. Štai kaip tai padaryti teisingai.",
    },
    date: "2025-11-24",
    readingTime: {
      en: "12 min read",
      lt: "12 min trukmės",
    },
    tags: {
      en: ["Content", "Structure", "Conversion"],
      lt: ["Turinys", "Struktūra", "Konversija"],
    },
    content: {
      en: [
        "Visitors scan, they don't read. Use clear headings, short paragraphs, and visual hierarchy to guide them to your CTA.",
        "I've seen beautiful websites with terrible conversion rates. The design is stunning, the animations are smooth, the colors are perfect. But visitors don't know what to do. They leave confused. Meanwhile, I've seen ugly websites with great structure that convert like crazy.",
        "Structure beats design every time. A well-structured page with basic design converts better than a beautiful page with poor structure. Here's why: structure guides action. Design creates emotion. You need both, but structure is the foundation.",
        "The best structure: problem → solution → proof → action. Every section should answer 'why should I care?' before moving forward. Start with the problem your visitor has. Make it clear you understand their pain. Then present your solution. Show proof it works. Finally, tell them exactly what to do next.",
        "Headings are your roadmap. Visitors scan headings to decide if they should keep reading. Use H1 for your main value proposition. Use H2 for major sections. Use H3 for subsections. Make them descriptive, not clever. 'How We Help' is better than 'Our Magic'.",
        "Short paragraphs win. Long blocks of text are intimidating. Break them up. One idea per paragraph. Three to four sentences max. This makes your content scannable. Visitors can quickly find what they need.",
        "Visual hierarchy matters. Important information should be bigger, bolder, or in a different color. Your CTA button should stand out. Your headline should be the biggest text on the page. Supporting information should be smaller. This guides the eye naturally.",
        "Use bullet points and lists. They're easy to scan. They break up text. They make information digestible. Instead of a paragraph explaining three benefits, use a bulleted list. Visitors can quickly see all three points.",
        "White space is structure too. Don't cram everything together. Give each section room to breathe. Space between sections helps visitors understand where one idea ends and another begins. Crowded pages feel overwhelming. Spacious pages feel organized.",
        "The F-pattern is real. Visitors scan in an F shape: across the top, down the left side, then across again. Put your most important information along this path. Headline at the top. Key points on the left. CTA where the second horizontal line would be.",
        "Above the fold matters less than you think. Yes, your headline and hero should be strong. But visitors will scroll if you give them a reason. Use your first screen to hook them, then use structure to keep them engaged as they scroll.",
        "Social proof should come after you've explained your solution. Don't lead with testimonials—lead with value. Once visitors understand what you do, then show them that others have benefited. Testimonials without context don't convert.",
        "Every section should have a purpose. If a section doesn't move visitors toward your goal, remove it. I see pages with 'About Our Team' sections that have nothing to do with conversion. Unless your team is the differentiator, it's just noise.",
        "Test your structure by removing all styling. If the page still makes sense and guides users to action, you've nailed it. Strip away colors, fonts, images. Just look at the text and headings. Can you still understand the flow? Can you still see what action to take? If yes, your structure is solid.",
        "One client had a gorgeous homepage with 12 sections. Conversion rate was 1.2%. We restructured it to 4 clear sections following problem → solution → proof → action. Same content, better organization. Conversion rate jumped to 4.8%. Structure made the difference.",
        "Mobile structure is even more important. On a small screen, you have less room to work with. Clear headings become critical. Short paragraphs are essential. Visual hierarchy is non-negotiable. If your structure doesn't work on mobile, you're losing most of your traffic.",
        "Start with your current homepage. Print it out or take a screenshot. Draw boxes around each section. Label each box: what is its purpose? Does it solve a problem, present a solution, show proof, or drive action? If a section doesn't fit any category, question whether you need it.",
        "Then reorganize. Put problem first. Then solution. Then proof. Then action. Within each section, use clear headings, short paragraphs, and visual hierarchy. Test it. You'll see the difference immediately.",
        "Beautiful design gets attention. Good structure gets conversions. You need both, but never sacrifice structure for design. Structure is the foundation. Design is the decoration. Build the foundation first, then decorate.",
      ],
      lt: [
        "Lankytojai peržvelgia, jie neskaito. Naudokite aiškias antraštes, trumpus pastraipas ir vizualinę hierarchiją, kad nukreiptumėte juos į jūsų CTA.",
        "Mačiau gražias svetaines su baisiais konversijos rodikliais. Dizainas stulbinantis, animacijos sklandžios, spalvos tobulos. Bet lankytojai nežino, ką daryti. Jie išeina sumišę. Tuo tarpu mačiau baisias svetaines su puikia struktūra, kurios konvertuoja kaip beprotiškos.",
        "Struktūra visada įveikia dizainą. Gerai struktūruotas puslapis su pagrindiniu dizainu konvertuoja geriau nei gražus puslapis su prasta struktūra. Štai kodėl: struktūra veda veiksmą. Dizainas sukuria emociją. Jums reikia abiejų, bet struktūra yra pagrindas.",
        "Geriausia struktūra: problema → sprendimas → įrodymas → veiksmas. Kiekviena sekcija turėtų atsakyti į 'kodėl man tai rūpi?' prieš einant toliau. Pradėkite nuo problemos, kurią turi jūsų lankytojas. Aiškiai parodykite, kad suprantate jų skausmą. Tada pateikite savo sprendimą. Parodykite įrodymą, kad jis veikia. Galiausiai pasakykite jiems tiksliai, ką daryti toliau.",
        "Antraštės yra jūsų kelrodis. Lankytojai peržvelgia antraštes, kad nuspręstų, ar turėtų toliau skaityti. Naudokite H1 savo pagrindiniam vertės pasiūlymui. Naudokite H2 pagrindinėms sekcijoms. Naudokite H3 posekcijoms. Padarykite jas aprašomąsias, ne protingas. 'Kaip Mes Padedame' yra geriau nei 'Mūsų Magija'.",
        "Trumpos pastraipos laimi. Ilgi teksto blokai yra bauginantys. Suskaidykite juos. Viena idėja per pastraipą. Maksimaliai trys ar keturi sakiniai. Tai daro jūsų turinį peržvelgiamą. Lankytojai gali greitai rasti tai, ko reikia.",
        "Vizualinė hierarchija svarbi. Svarbi informacija turėtų būti didesnė, storesnė arba kitos spalvos. Jūsų CTA mygtukas turėtų išsiskirti. Jūsų antraštė turėtų būti didžiausias tekstas puslapyje. Palaikanti informacija turėtų būti mažesnė. Tai natūraliai veda akį.",
        "Naudokite sąrašus ir punktus. Jie lengvai peržvelgiami. Jie suskaido tekstą. Jie daro informaciją suvokiamą. Vietoj pastraipos, aiškinančios tris naudas, naudokite sąrašą. Lankytojai gali greitai pamatyti visus tris punktus.",
        "Balta erdvė taip pat yra struktūra. Neverskite visko kartu. Duokite kiekvienai sekcijai erdvės kvėpuoti. Tarpas tarp sekcijų padeda lankytojams suprasti, kur baigiasi viena idėja ir prasideda kita. Perpildyti puslapiai atrodo persunkę. Erdvūs puslapiai atrodo organizuoti.",
        "F-modelis yra tikras. Lankytojai peržvelgia F formos: per viršų, žemyn kairėje pusėje, tada vėl per. Įdėkite svarbiausią informaciją šiuo keliu. Antraštė viršuje. Pagrindiniai punktai kairėje. CTA ten, kur būtų antra horizontalė.",
        "Virš ekrano svarbu mažiau nei manote. Taip, jūsų antraštė ir hero turėtų būti stiprūs. Bet lankytojai slinks, jei duosite jiems priežastį. Naudokite savo pirmą ekraną, kad juos užkabintumėte, tada naudokite struktūrą, kad juos užlaikytumėte slinkdami.",
        "Socialinis įrodymas turėtų ateiti po to, kai paaiškinote savo sprendimą. Nenukreipkite su atsiliepimais—nukreipkite su verte. Kai lankytojai supranta, ką darote, tada parodykite jiems, kad kiti naudojosi. Atsiliepimai be konteksto nekonvertuoja.",
        "Kiekviena sekcija turėtų turėti tikslą. Jei sekcija neveda lankytojų link jūsų tikslo, pašalinkite ją. Matau puslapius su 'Apie Mūsų Komandą' sekcijomis, kurios neturi nieko bendro su konversija. Nebent jūsų komanda yra diferenciatorius, tai tiesiog triukšmas.",
        "Išbandykite savo struktūrą pašalindami visą stilių. Jei puslapis vis dar turi prasmę ir veda vartotojus į veiksmą, jūs tai įveikėte. Nuimkite spalvas, šriftus, vaizdus. Tiesiog pažiūrėkite į tekstą ir antraštes. Ar vis dar galite suprasti srautą? Ar vis dar matote, kokį veiksmą imtis? Jei taip, jūsų struktūra yra tvirta.",
        "Vienas klientas turėjo puikų pagrindinį puslapį su 12 sekcijų. Konversijos rodiklis buvo 1,2%. Perorganizavome jį į 4 aiškias sekcijas, vadovaudamiesi problema → sprendimas → įrodymas → veiksmas. Tas pats turinys, geresnė organizacija. Konversijos rodiklis šoko iki 4,8%. Struktūra padarė skirtumą.",
        "Mobilioji struktūra dar svarbesnė. Mažame ekrane turite mažiau vietos dirbti. Aiškios antraštės tampa kritinės. Trumpos pastraipos yra būtinos. Vizualinė hierarchija yra neaptariama. Jei jūsų struktūra neveikia mobiliajame, prarandate didžiąją dalį savo srauto.",
        "Pradėkite nuo savo dabartinio pagrindinio puslapio. Išspausdinkite arba nufotografuokite. Nubrėžkite langus aplink kiekvieną sekciją. Pažymėkite kiekvieną langą: koks jo tikslas? Ar jis sprendžia problemą, pateikia sprendimą, rodo įrodymą arba skatina veiksmą? Jei sekcija netelpa jokiai kategorijai, klausykite, ar jums jos reikia.",
        "Tada reorganizuokite. Įdėkite problemą pirmą. Tada sprendimą. Tada įrodymą. Tada veiksmą. Kiekvienoje sekcijoje naudokite aiškias antraštes, trumpas pastraipas ir vizualinę hierarchiją. Išbandykite. Pamatysite skirtumą nedelsiant.",
        "Gražus dizainas pritraukia dėmesį. Geras struktūra gauna konversijas. Jums reikia abiejų, bet niekada neaukokite struktūros dėl dizaino. Struktūra yra pagrindas. Dizainas yra dekoracija. Pirmiausia pastatykite pagrindą, tada dekoruokite.",
      ],
    },
  },
  {
    slug: "seo-foundations-for-small-business-owners",
    title: {
      en: "SEO Foundations Every Small Business Owner Should Nail",
      lt: "SEO pagrindai, kuriuos turėtų įvaldyti kiekvienas smulkaus verslo savininkas",
    },
    summary: {
      en: "Forget advanced hacks. These are the five fundamentals that deliver measurable search traffic without hiring a massive agency.",
      lt: "Pamirškite sudėtingus triukus. Šie penki pagrindai suteikia matomą paieškos srautą be didžiųjų agentūrų samdymo.",
    },
    date: "2025-11-17",
    readingTime: {
      en: "11 min read",
      lt: "11 min trukmės",
    },
    tags: {
      en: ["SEO", "Growth"],
      lt: ["SEO", "Augimas"],
    },
    content: {
      en: [
        "Search is compound interest. Nail the boring basics and you will outrun 90% of your local competition.",
        "I see small business owners get overwhelmed by SEO advice. They read about schema markup, technical SEO audits, and link building strategies. Then they do nothing because it all seems too complicated. Here's the truth: you don't need any of that to start ranking.",
        "1) Clarify a primary keyword for each core page. Your homepage should target your main service or product. Your about page should target 'your business name' or 'your location + service'. Your services pages should each target one specific service. Don't try to rank for everything on one page—that's how you rank for nothing.",
        "Research doesn't have to be complicated. Type your keyword into Google. See what comes up. Read the top 3 results. What questions are they answering? What words do they use? That's your starting point. Tools like Ubersuggest or Answer The Public can help, but Google itself is your best teacher.",
        "2) Ship useful on-page copy that actually answers questions. Google ranks pages that help people. If someone searches 'best plumber in Vilnius' and lands on your page, they should immediately see: yes, you are a plumber, yes, you serve Vilnius, and yes, here's why you're good at it.",
        "Write for humans first, keywords second. Stuffing your page with 'plumber plumber plumber' doesn't work anymore. Instead, write naturally about what you do. Use your keyword in the title, in the first paragraph, and a few times throughout. But make sure every sentence adds value.",
        "3) Make the site fast on mobile. Google cares about speed. If your site takes 5 seconds to load on a phone, you're losing rankings and customers. Use tools like PageSpeed Insights to check your score. Aim for 90+ on mobile. If you're below 70, you have work to do.",
        "Common speed killers: huge images, too many plugins, unoptimized code. Fix images first—compress them, use WebP format, lazy load below-the-fold content. This alone can cut load time in half.",
        "4) Connect Search Console and watch queries weekly. Search Console is free and tells you exactly what people are searching for to find your site. Check it every Monday. See which queries are bringing traffic. See which pages are ranking. Then optimize those pages further.",
        "If you see a query with high impressions but low clicks, that's an opportunity. Your page is showing up but not compelling enough. Improve the title tag and meta description to match what people are actually searching for.",
        "5) Build one meaningful backlink each month. A backlink is when another website links to yours. Google sees this as a vote of confidence. One good backlink from a local business directory or industry publication is worth more than 100 spammy directory submissions.",
        "Start local: get listed in your local chamber of commerce directory, your industry association's member list, or a local business guide. Then reach out to local blogs or news sites. Offer to write a guest post or provide expert commentary. One quality link per month compounds over time.",
        "Everything else (AI content, massive link swaps) is optional. Discipline beats gimmicks. I've seen businesses rank #1 for competitive keywords just by doing these five things consistently for 6 months. No fancy tools, no expensive agencies, just consistent execution of the basics.",
      ],
      lt: [
        "Paieška yra sudėtinės palūkanos. Įvaldykite nuobodžius pagrindus ir aplenksite 90% vietinės konkurencijos.",
        "Matau, kaip smulkaus verslo savininkai persikrauna nuo SEO patarimų. Jie skaito apie schema markup, techninį SEO auditu ir nuorodų kūrimo strategijas. Tada jie nieko nedaro, nes viskas atrodo per sudėtinga. Štai tiesa: jums nereikia nieko iš to, kad pradėtumėte reitinguotis.",
        "1) Išaiškinkite pagrindinį raktažodį kiekvienam svarbiausiam puslapiui. Jūsų pagrindinis puslapis turėtų tiksinti jūsų pagrindinę paslaugą ar produktą. Jūsų apie puslapis turėtų tiksinti 'jūsų verslo pavadinimą' arba 'jūsų vietą + paslaugą'. Jūsų paslaugų puslapiai turėtų kiekvienas tiksinti vieną specifinę paslaugą. Nemėginkite reitinguotis viskam viename puslapyje—taip jūs nereitinguojatės niekam.",
        "Tyrimas neturi būti sudėtingas. Įveskite savo raktažodį į Google. Pamatykite, kas pasirodo. Perskaitykite top 3 rezultatus. Kokius klausimus jie atsako? Kokius žodžius jie naudoja? Tai jūsų pradžios taškas. Įrankiai kaip Ubersuggest arba Answer The Public gali padėti, bet pats Google yra jūsų geriausias mokytojas.",
        "2) Sukurkite naudingą puslapio turinį, kuris tikrai atsako į klausimus. Google reitinguoja puslapius, kurie padeda žmonėms. Jei kas nors ieško 'geriausias santechnikas Vilniuje' ir patenka į jūsų puslapį, jie turėtų nedelsiant matyti: taip, jūs esate santechnikas, taip, jūs aptarnaujate Vilnių, ir taip, štai kodėl jūs esate geri.",
        "Rašykite pirmiausia žmonėms, antra raktažodžiams. Puslapio užpildymas 'santechnikas santechnikas santechnikas' jau nebeveikia. Vietoj to, rašykite natūraliai apie tai, ką darote. Naudokite savo raktažodį antraštėje, pirmoje pastraipoje ir kelis kartus visame tekste. Bet užtikrinkite, kad kiekvienas sakinys prideda vertės.",
        "3) Padarykite svetainę greitą mobiliajame. Google rūpi greitis. Jei jūsų svetainė kraunasi 5 sekundes telefone, jūs prarandate reitingus ir klientus. Naudokite įrankius kaip PageSpeed Insights, kad patikrintumėte savo rezultatą. Siekite 90+ mobiliajame. Jei esate žemiau 70, turite darbo.",
        "Dažni greičio žudikliai: dideli vaizdai, per daug papildinių, neoptimizuotas kodas. Pirmiausia ištaisykite vaizdus—suspaudžiate juos, naudokite WebP formatą, tingiai kraukite turinį žemiau ekrano. Vien tai gali sumažinti įkėlimo laiką perpus.",
        "4) Prijunkite Search Console ir stebėkite užklausas kas savaitę. Search Console yra nemokama ir pasako jums tiksliai, ką žmonės ieško, kad rastų jūsų svetainę. Patikrinkite kiekvieną pirmadienį. Pamatykite, kurios užklausos atneša srautą. Pamatykite, kurie puslapiai reitinguojasi. Tada toliau optimizuokite tuos puslapius.",
        "Jei matote užklausą su didelėmis impresijomis, bet mažais paspaudimais, tai galimybė. Jūsų puslapis pasirodo, bet nėra pakankamai patrauklus. Pagerinkite title tag ir meta aprašymą, kad atitiktų tai, ką žmonės tikrai ieško.",
        "5) Sukurkite vieną prasmingą atgalinę nuorodą kiekvieną mėnesį. Atgalinė nuoroda yra tada, kai kita svetainė nuoroda į jūsų. Google tai mato kaip pasitikėjimo balsą. Viena gera atgalinė nuoroda iš vietinio verslo katalogo ar pramonės leidinio verta daugiau nei 100 šlamštiškų katalogo pateikimų.",
        "Pradėkite vietiškai: įtraukite į savo vietinės prekybos rūmų katalogą, savo pramonės asociacijos narių sąrašą arba vietinį verslo vadovą. Tada susisiekite su vietiniais tinklaraščiais ar naujienų svetainėmis. Pasiūlykite parašyti svečio straipsnį arba pateikti ekspertinį komentarą. Viena kokybiška nuoroda per mėnesį laikui bėgant kaupiasi.",
        "Viskas kita (AI turinys, masiniai nuorodų pasikeitimai) yra neprivaloma. Disciplina įveikia gudrybes. Mačiau verslus, reitinguojančius #1 konkurencingiems raktažodžiams, tiesiog nuosekliai atlikdami šiuos penkis dalykus 6 mėnesius. Jokių įmantrių įrankių, jokių brangių agentūrų, tik nuoseklus pagrindinių dalykų įgyvendinimas.",
      ],
    },
  },
  {
    slug: "meta-ads-lessons-from-early-campaigns",
    title: {
      en: "3 Lessons From Running Early Meta Ads Campaigns Under Supervision",
      lt: "3 pamokos iš ankstyvesnių Meta reklamos kampanijų valdymų",
    },
    summary: {
      en: "What small business owners should know before putting €1 into paid social, based on campaigns I run with an experienced mentor.",
      lt: "Ką smulkaus verslo savininkai turėtų žinoti prieš įdėdami €1 į mokamą socialinę reklamą, remiantis kampanijomis, kurias vykdau su patyrusiu mentoriumi.",
    },
    date: "2025-11-06",
    readingTime: {
      en: "10 min read",
      lt: "10 min trukmės",
    },
    tags: {
      en: ["Paid Media", "Meta Ads"],
      lt: ["Mokama Rinkodara", "Meta Reklama"],
    },
    content: {
      en: [
        "I started running Meta ads campaigns under the supervision of an experienced mentor, and the lessons were immediate. What I thought I knew about paid social was mostly wrong. Here's what actually works for small businesses.",
        "Lesson one: creative fatigue is real. Rotate hooks weekly even at low spend. Your ad might be performing great in week one, but by week three, the same people have seen it too many times. They scroll past. Your CTR drops. Your cost per click goes up.",
        "The solution isn't complicated: create 3-5 variations of your ad creative upfront. Use different headlines, different images, different angles. Then rotate them weekly. When one starts to fatigue, pause it and launch a fresh one. This keeps your campaigns fresh without constant creative work.",
        "I learned this the hard way. One ad was crushing it for two weeks—2.5% CTR, €0.15 cost per click. Then week three hit and everything tanked. Same ad, same audience, but performance dropped 60%. That's creative fatigue. Now I always have backups ready.",
        "Lesson two: broad targeting beats hyper-specific interests when your pixel is fresh. Let the algorithm explore. When you first start running ads, Meta's pixel doesn't know who your best customers are. Narrow targeting with 5+ interest layers sounds smart, but it limits the algorithm's ability to learn.",
        "Start broad. Let Meta show your ad to different people. The algorithm will quickly figure out who converts and who doesn't. After 50-100 conversions, you can start narrowing. But in the beginning, give it room to breathe.",
        "I made the mistake of hyper-targeting early campaigns. I selected 'small business owners' + 'marketing' + 'web design' + 'Vilnius' + 'ages 30-45'. The audience was tiny—maybe 5,000 people. The algorithm had no room to optimize. Results were mediocre.",
        "Then I tried broad targeting: just 'Vilnius' and 'ages 25-55'. The audience jumped to 200,000+. The algorithm found people I never would have thought to target. Conversion rate improved. Cost per acquisition dropped. The algorithm is smarter than we give it credit for.",
        "Lesson three: always define a KPI you can measure this week. If you can't see it in Ads Manager, it's vanity. 'Brand awareness' sounds nice, but you can't measure it this week. 'Website clicks' is measurable, but does it matter if no one converts?",
        "For most small businesses, the KPI should be conversions: form submissions, purchases, phone calls—something that leads to revenue. Set up your pixel correctly. Track the events that matter. Then optimize for those events.",
        "I see business owners track impressions and reach. Those numbers look impressive, but they don't pay bills. Focus on what moves the needle: leads, sales, sign-ups. Everything else is noise.",
        "One client wanted to track 'engagement' as their KPI. I asked: what does engagement mean? Likes? Comments? Shares? None of those lead to sales. We switched to tracking form submissions. Within two weeks, we had clear data on what was working. We doubled down on winning ads and cut losers. Results improved immediately.",
        "Bonus lesson: patience pays. Meta's algorithm needs data to optimize. Don't kill a campaign after 3 days because it's not profitable yet. Give it at least 7-10 days and 20+ conversions before making major changes. The algorithm gets smarter with more data.",
        "These three lessons transformed how I approach Meta ads. Creative rotation prevents fatigue. Broad targeting lets the algorithm learn. Clear KPIs keep you focused on what matters. Everything else is just noise.",
      ],
      lt: [
        "Pradėjau vykdyti Meta reklamos kampanijas patyrusio mentoriaus priežiūroje, ir pamokos buvo akimirksniniai. Tai, ką maniau žinoti apie mokamą socialinę reklamą, daugiausia buvo neteisinga. Štai kas tikrai veikia smulkaus verslo atveju.",
        "Pirma pamoka: kūrybinis nuovargis yra tikras. Keiskite hook'us kas savaitę, net ir turint mažesnias pajamas. Jūsų reklama gali puikiai veikti pirmą savaitę, bet trečią savaitę tie patys žmonės jau per daug kartų ją matė. Jie praskroliuoja. Jūsų CTR krenta. Jūsų kaina už paspaudimą auga.",
        "Sprendimas nėra sudėtingas: iš anksto sukurkite 3-5 jūsų reklamos kūrybos variantus. Naudokite skirtingas antraštes, skirtingus vaizdus, skirtingus kampus. Tada keiskite juos kas savaitę. Kai vienas pradeda nuvargti, sustabdykite jį ir paleiskite naują. Tai palaiko jūsų kampanijas šviežias be nuolatinio kūrybinio darbo.",
        "Aš tai išmokau sunkiu būdu. Viena reklama dvejus savaites veikė puikiai—2,5% CTR, €0,15 kaina už paspaudimą. Tada prasidėjo trečia savaitė ir viskas nukrito. Ta pati reklama, ta pati auditorija, bet veikimas sumažėjo 60%. Tai kūrybinis nuovargis. Dabar visada turiu atsarginių kopijų.",
        "Antra pamoka: platus tikslinimas įveikia itin specifinius interesus, kai jūsų pikselis yra naujas. Leiskite algoritmui tyrinėti. Kai pirmą kartą pradedate vykdyti reklamą, Meta pikselis nežino, kas yra jūsų geriausi klientai. Siauras tikslinimas su 5+ interesų sluoksniais skamba protingai, bet tai riboja algoritmo galimybę mokytis.",
        "Pradėkite plačiai. Leiskite Meta rodyti jūsų reklamą skirtingiems žmonėms. Algoritmas greitai išsiaiškins, kas konvertuoja, o kas ne. Po 50-100 konversijų galite pradėti siaurinti. Bet pradžioje duokite jam erdvės kvėpuoti.",
        "Padariau klaidą hiper-tikslinant ankstesnes kampanijas. Pasirinkau 'smulkaus verslo savininkai' + 'rinkodara' + 'svetainių dizainas' + 'Vilnius' + 'amžius 30-45'. Auditorija buvo maža—galbūt 5,000 žmonių. Algoritmas neturėjo vietos optimizuoti. Rezultatai buvo vidutiniški.",
        "Tada išbandžiau platų tikslinimą: tiesiog 'Vilnius' ir 'amžius 25-55'. Auditorija šoko iki 200,000+. Algoritmas rado žmonių, kurių niekada nebūčiau galvojęs tiksinti. Konversijos rodiklis pagerėjo. Kaina už įgijimą sumažėjo. Algoritmas yra protingesnis nei mes jam suteikiame kredito.",
        "Trečia pamoka: visada apibrėžkite KPI, kurį galite išmatuoti šią savaitę. Jei jo neturi Ads Manager, vadinasi neseki rezultatų. 'Prekės ženklo žinomybė' skamba gražiai, bet negalite jos išmatuoti šią savaitę. 'Svetainės paspaudimai' yra išmatuojami, bet ar tai svarbu, jei niekas nekonvertuoja?",
        "Daugumai smulkaus verslo KPI turėtų būti konversijos: formos pateikimai, pirkimai, telefono skambučiai—kažkas, kas veda į pajamas. Teisingai nustatykite savo pikselį. Stebėkite svarbius įvykius. Tada optimizuokite tuos įvykius.",
        "Matau verslo savininkus, stebinčius impresijas ir pasiekiamumą. Tie skaičiai atrodo įspūdingi, bet jie nemoka sąskaitų. Sutelkite dėmesį į tai, kas keičia rodiklius: potencialūs klientai, pardavimai, registracijos. Viskas kita yra triukšmas.",
        "Vienas klientas norėjo stebėti 'įsitraukimą' kaip savo KPI. Paklausiau: ką reiškia įsitraukimas? Patinka? Komentarai? Dalijimasis? Nė vienas iš jų neveda į pardavimus. Perėjome prie formos pateikimų stebėjimo. Per dvi savaites turėjome aiškius duomenis apie tai, kas veikia. Sustiprinome laimėtojus ir nutraukėme pralaimėtojus. Rezultatai pagerėjo nedelsiant.",
        "Papildoma pamoka: kantrybė atsiperka. Meta algoritmui reikia duomenų optimizuoti. Nenutraukite kampanijos po 3 dienų, nes ji dar nepelninga. Duokite jai bent 7-10 dienų ir 20+ konversijų prieš darydami didelius pakeitimus. Algoritmas tampa protingesnis su daugiau duomenų.",
        "Šios trys pamokos pakeitė, kaip aš žiūriu į Meta reklamą. Kūrybinis rotavimas apsaugo nuo nuovargio. Platus tikslinimas leidžia algoritmui mokytis. Aiškūs KPI laiko jūsų dėmesį svarbiausiems dalykams. Viskas kita yra tiesiog triukšmas.",
      ],
    },
  },
  {
    slug: "why-simple-websites-convert-better",
    title: {
      en: "Why Simple Websites Convert Better Than Complex Ones",
      lt: "Kodėl paprastos svetainės konvertuoja geriau už sudėtingas",
    },
    summary: {
      en: "Less is more when it comes to conversions. Here's why stripping down your website to essentials drives better results.",
      lt: "Mažiau yra daugiau, kai kalbame apie konversijas. Štai kodėl supaprastinimas iš esmės duoda geresnius rezultatus.",
    },
    date: "2025-10-30",
    readingTime: {
      en: "10 min read",
      lt: "10 min trukmės",
    },
    tags: {
      en: ["Conversion", "Design", "UX"],
      lt: ["Konversija", "Dizainas", "Vartotojo Patirtis"],
    },
    content: {
      en: [
        "Every extra button, animation, or section is a decision point. More decisions mean more opportunities for visitors to leave.",
        "I've tested this with dozens of clients. The pattern is consistent: simpler pages convert better. Not because they're prettier—because they're clearer. When someone lands on your site, they should know within 3 seconds what you do and what you want them to do.",
        "Complex websites try to show everything. They have navigation menus with 10 items, hero sections with 5 CTAs, feature lists with 20 bullet points. This is decision paralysis. Visitors see too many options and choose none.",
        "Simple websites focus on one goal: get the visitor to take action. No distractions, no confusion, just a clear path forward. Think of your website like a funnel. Every element should guide visitors toward your primary goal: book a call, request a quote, make a purchase.",
        "Here's what I mean by simple: one clear headline that states your value proposition. One hero image or video that supports that message. One primary CTA button that's impossible to miss. Supporting content below, but the main action is always visible.",
        "I redesigned a client's homepage that had 8 different CTAs scattered across the page. They were getting 2% conversion rate. We cut it down to one primary CTA and moved everything else below the fold. Conversion rate jumped to 5.2%. Same traffic, same offer, just less noise.",
        "Animations and effects can be tempting. They look cool. But every animation is a distraction. A subtle fade-in is fine. A complex parallax scroll that makes text hard to read? That's hurting conversions. Every design element should serve the goal, not just look impressive.",
        "White space is your friend. Don't fill every pixel. Give your content room to breathe. This makes it easier to scan, easier to read, easier to understand. Crowded pages feel overwhelming. Spacious pages feel trustworthy.",
        "Test it yourself: remove half the elements from your homepage. You'll likely see conversion rates improve because visitors know exactly what to do next. I'm serious—take a screenshot of your current homepage, then delete half the sections. Does it still communicate your core message? If yes, you probably didn't need those sections.",
        "The psychology is simple: fewer choices = faster decisions. When Amazon reduced their checkout from multiple steps to one click, sales increased. When Google simplified their homepage to just a search bar, usage exploded. Simplicity wins.",
        "This doesn't mean your site has to be boring. It means every element needs a purpose. Beautiful design that doesn't convert is just expensive decoration. Simple design that converts is smart business.",
        "One more thing: mobile users have even less patience. On a phone, you have maybe 2 seconds to communicate value before they scroll away. Simple, clear messaging wins every time. Complex layouts with multiple columns and sections? They just create friction.",
        "Start with your homepage. What's the one thing you want visitors to do? Make that action obvious. Remove everything that doesn't support it. Then test. You'll be surprised how much better simple performs.",
      ],
      lt: [
        "Kiekvienas papildomas mygtukas, animacija ar sekcija yra sprendimo taškas. Daugiau sprendimų reiškia daugiau galimybių lankytojams išeiti.",
        "Aš tai išbandžiau su dešimtimis klientų. Modelis yra nuoseklus: paprastesni puslapiai konvertuoja geriau. Ne todėl, kad jie gražesni—nes jie aiškesni. Kai kas nors patenka į jūsų svetainę, jie turėtų per 3 sekundes žinoti, ką darote ir ko norite.",
        "Sudėtingos svetainės bando parodyti viską. Jos turi navigacijos meniu su 10 elementų, hero sekcijas su 5 CTA, funkcijų sąrašus su 20 punktų. Tai sprendimų paralyžius. Lankytojai mato per daug galimybių ir renkasi nieko.",
        "Paprastos svetainės sutelkia dėmesį į vieną tikslą: priversti lankytoją imtis veiksmų. Jokių išsiblaškymų, jokio painiavos, tik aiškus kelias į priekį. Pagalvokite apie savo svetainę kaip apie piltuvą. Kiekvienas elementas turėtų vesti lankytojus link jūsų pagrindinio tikslo: užsakyti skambutį, užsakyti pasiūlymą, atlikti pirkimą.",
        "Štai ką turiu omenyje paprastu: viena aiški antraštė, nurodanti jūsų vertės pasiūlymą. Vienas hero vaizdas arba vaizdo įrašas, palaikantis tą žinutę. Vienas pagrindinis CTA mygtukas, kurio neįmanoma nepastebėti. Palaikantis turinys žemiau, bet pagrindinis veiksmas visada matomas.",
        "Perdizainavau kliento pagrindinį puslapį, kuris turėjo 8 skirtingus CTA, išsibarsčiusius po puslapį. Jie gaudavo 2% konversijos rodiklį. Sumažinome iki vieno pagrindinio CTA ir perkėlėme viską kitą žemiau. Konversijos rodiklis šoko iki 5,2%. Tas pats srautas, tas pats pasiūlymas, tiesiog mažiau triukšmo.",
        "Animacijos ir efektai gali būti viliojantys. Jie atrodo šauniai. Bet kiekviena animacija yra išsiblaškymas. Subtilus išnykimas yra gerai. Sudėtingas paralaksinis slinkimas, dėl kurio tekstą sunku skaityti? Tai kenkia konversijoms. Kiekvienas dizaino elementas turėtų tarnauti tikslui, ne tik atrodyti įspūdingai.",
        "Balta erdvė yra jūsų draugas. Neužpildykite kiekvieno pikselio. Duokite savo turiniui erdvės kvėpuoti. Tai palengvina peržiūrą, skaitymą, supratimą. Perpildyti puslapiai atrodo persunkę. Erdvūs puslapiai atrodo patikimi.",
        "Išbandykite patys: pašalinkite pusę elementų iš pagrindinio puslapio. Greičiausiai pamatysite, kad konversijos rodikliai pagerės, nes lankytojai tiksliai žino, ką daryti toliau. Rimtai—nufotografuokite savo dabartinį pagrindinį puslapį, tada ištrinkite pusę sekcijų. Ar jis vis dar perduoda jūsų pagrindinę žinutę? Jei taip, greičiausiai jums nereikėjo tų sekcijų.",
        "Psichologija paprasta: mažiau pasirinkimų = greitesni sprendimai. Kai Amazon sumažino savo apmokėjimą nuo kelių žingsnių iki vieno paspaudimo, pardavimai padidėjo. Kai Google supaprastino savo pagrindinį puslapį iki tik paieškos juostos, naudojimas sprogo. Paprastumas laimi.",
        "Tai nereiškia, kad jūsų svetainė turi būti nuobodi. Tai reiškia, kad kiekvienas elementas turi turėti tikslą. Gražus dizainas, kuris nekonvertuoja, yra tiesiog brangi dekoracija. Paprastas dizainas, kuris konvertuoja, yra protingas verslas.",
        "Dar vienas dalykas: mobilieji vartotojai turi dar mažiau kantrybės. Telefone turite galbūt 2 sekundes perduoti vertę, prieš jie praskroliuoja. Paprastas, aiškus pranešimas laimi kiekvieną kartą. Sudėtingi maketai su keliais stulpeliais ir sekcijomis? Jie tiesiog sukuria trintį.",
        "Pradėkite nuo savo pagrindinio puslapio. Ką vieną dalyką norite, kad lankytojai darytų? Padarykite tą veiksmą akivaizdų. Pašalinkite viską, kas to nepalaiko. Tada išbandykite. Nustebsite, kiek geriau paprastas veikia.",
      ],
    },
  },
  {
    slug: "mobile-first-design-is-not-optional",
    title: {
      en: "Mobile-First Design Is Not Optional Anymore",
      lt: "Mobilusis dizainas nebėra pasirenkamas",
    },
    summary: {
      en: "Over 60% of web traffic is mobile. If your site doesn't work perfectly on phones, you're losing customers before they even see your offer.",
      lt: "Daugiau nei 60% interneto srauto yra iš mobiliųjų įrenginių. Jei jūsų svetainė neveikia puikiai telefonuose, prarandate klientus dar prieš jiem pamačius jūsų pasiūlymą.",
    },
    date: "2025-10-28",
    readingTime: {
      en: "11 min read",
      lt: "11 min trukmės",
    },
    tags: {
      en: ["Mobile", "Design", "Performance"],
      lt: ["Mobilusis", "Dizainas", "Veikimas"],
    },
    content: {
      en: [
        "Over 60% of web traffic is mobile. If your site doesn't work perfectly on phones, you're losing customers before they even see your offer.",
        "I see businesses spend months perfecting their desktop experience, then throw together a mobile version as an afterthought. This is backwards. Mobile should come first, not last.",
        "Mobile-first doesn't mean mobile-only. It means starting with the smallest screen and building up. This forces you to prioritize what actually matters. When you only have 375 pixels wide, you can't fit everything. You have to choose. That choice makes your site better on all devices.",
        "The process is simple: design for mobile first. Get the layout, copy, and flow working perfectly on a phone. Then expand it for tablets. Then expand it for desktop. Each step adds, it doesn't subtract. You're building up, not scaling down.",
        "When you design desktop-first, you're making decisions based on having lots of space. Then you try to cram it all into a mobile screen. Things get hidden, menus get complicated, text gets tiny. It's a compromise, and compromises hurt conversions.",
        "Test every page on a real phone, not just browser dev tools. What looks fine on desktop can be unusable on mobile. Dev tools are great for debugging, but they don't show you how it actually feels to use your site on a phone.",
        "I test on my actual iPhone. I check button sizes—can I tap them easily with my thumb? I check text size—can I read it without zooming? I check load time—does it feel fast or sluggish? These are the questions that matter, and you can't answer them in a desktop browser.",
        "Touch targets need to be bigger. On desktop, a 20px button works fine. On mobile, you need at least 44px. Apple recommends 44x44px minimum. Google recommends 48x48px. Small buttons are frustrating. Users will miss taps, get frustrated, and leave.",
        "Text needs to be readable without zooming. 16px is the minimum for body text on mobile. Smaller than that, and users will struggle. They'll zoom in, which breaks the layout. They'll get frustrated. They'll leave.",
        "Speed matters more on mobile. A slow-loading site on mobile is worse than a slow site on desktop. Users will bounce in seconds. Mobile users are often on slower connections. They're often multitasking. They have less patience.",
        "Optimize images for mobile. Use WebP format. Compress aggressively. Serve smaller images to mobile devices. A 2MB hero image might look great on desktop, but it'll kill mobile performance. Use responsive images—serve the right size for the right device.",
        "Minimize JavaScript. Every script adds load time. Every script can break on mobile. Use only what you need. Lazy load everything below the fold. Defer non-critical scripts. Mobile users care about speed, not fancy animations.",
        "Navigation is different on mobile. Desktop menus with 10 items work fine. On mobile, they're a nightmare. Use a hamburger menu, but make sure it's easy to open and close. Or use a bottom navigation bar for key pages. Keep it simple.",
        "Forms are harder on mobile. Every extra field is friction. Keep forms short. Use the right input types (email, tel, number) so mobile keyboards match. Auto-fill helps, but only if your form is structured correctly.",
        "One client had a beautiful desktop site. Conversion rate was 3.2% on desktop. But mobile conversion was 0.8%. We redesigned mobile-first. Desktop conversion stayed the same, but mobile jumped to 2.9%. Same traffic, same offer, just better mobile experience.",
        "Google ranks mobile-friendly sites higher. If your site doesn't work well on mobile, you're hurting your SEO. Mobile-first design isn't just about conversions—it's about visibility.",
        "Start today. Open your site on your phone. Can you easily complete your main goal? If not, fix it. Mobile isn't optional anymore. It's essential.",
      ],
      lt: [
        "Daugiau nei 60% interneto srauto yra iš mobiliųjų įrenginių. Jei jūsų svetainė neveikia puikiai telefonuose, prarandate klientus dar prieš jiem pamačius jūsų pasiūlymą.",
        "Matau verslus, leidžiančius mėnesius tobulindami savo stacionaraus kompiuterio patirtį, tada surenkančius mobilų versiją kaip antraštę. Tai atvirkščiai. Mobilusis turėtų būti pirmas, ne paskutinis.",
        "Mobile-first, nereiškia darbas tik prie telefonų. Tai reiškia pradėti nuo mažiausio ekrano ir kurti aukštyn. Tai verčia prioritizuoti tai, kas tikrai svarbu. Kai turite tik 375 pikselių pločio, negalite tilpti visko. Turite rinktis. Tas pasirinkimas padaro jūsų svetainę geresnę visuose įrenginiuose.",
        "Procesas paprastas: dizainuokite pirmiausia mobiliesiems. Gaukite maketą, tekstą ir srautą puikiai veikiantį telefone. Tada išplėskite planšetėms. Tada išplėskite stacionariam kompiuteriui. Kiekvienas žingsnis prideda, ne atima. Jūs kuriate aukštyn, ne mažinate.",
        "Kai dizainuojate pirmiausia stacionariam kompiuteriui, darote sprendimus, remdamiesi turėdami daug vietos. Tada bandote viską suspausti į mobilų ekraną. Dalykai paslepiami, meniu tampa sudėtingi, tekstas tampa mažas. Tai kompromisas, o kompromisai kenkia konversijoms.",
        "Išbandykite kiekvieną puslapį tikrame telefone, ne tik naršyklės kūrimo įrankiuose. Kas atrodo gerai stacionariame kompiuteryje, gali būti nenaudojama mobiliajame. Kūrimo įrankiai puikūs derinimui, bet jie nerodo, kaip iš tikrųjų jaučiasi naudoti jūsų svetainę telefone.",
        "Aš išbandau savo tikrame iPhone. Patikrinu mygtukų dydžius—ar galiu juos lengvai paspausti nykščiu? Patikrinu teksto dydį—ar galiu jį skaityti be didinimo? Patikrinu įkėlimo laiką—ar jis atrodo greitas ar lėtas? Tai klausimai, kurie svarbūs, ir negalite jų atsakyti stacionariame naršyklėje.",
        "Lietimo taškai turi būti didesni. Stacionariame kompiuteryje 20px mygtukas veikia gerai. Mobiliajame reikia bent 44px. Apple rekomenduoja 44x44px minimumą. Google rekomenduoja 48x48px. Maži mygtukai yra varginantys. Vartotojai praleis paspaudimus, susinervins ir išeis.",
        "Tekstas turi būti skaitomas be didinimo. 16px yra minimumas pagrindiniam tekstui mobiliajame. Mažiau nei tai, ir vartotojai kentės. Jie padidins, kas sugadina maketą. Jie susinervins. Jie išeis.",
        "Greitis svarbesnis mobiliajame. Lėtai kraunačiojanti svetainė mobiliajame yra blogiau nei lėta svetainė stacionariame. Vartotojai išeis per sekundes. Mobilieji vartotojai dažnai naudoja lėtesnius ryšius. Jie dažnai atlieka kelias užduotis vienu metu. Jie turi mažiau kantrybės.",
        "Optimizuokite vaizdus mobiliajame. Naudokite WebP formatą. Suspaudžiate agresyviai. Tiekite mažesnius vaizdus mobiliems įrenginiams. 2MB hero vaizdas gali atrodyti puikiai stacionariame kompiuteryje, bet jis sunaikins mobilų veikimą. Naudokite reaguojančius vaizdus—tiekite tinkamą dydį tinkamam įrenginiui.",
        "Sumažinkite JavaScript. Kiekvienas scenarijus prideda įkėlimo laiką. Kiekvienas scenarijus gali sugesti mobiliajame. Naudokite tik tai, ko reikia. Tingiai kraukite viską žemiau ekrano. Atidėkite nekritinius scenarijus. Mobilieji vartotojai rūpi greitis, ne įmantrios animacijos.",
        "Navigacija skiriasi mobiliajame. Stacionaraus kompiuterio meniu su 10 elementų veikia gerai. Mobiliajame jie yra košmaras. Naudokite hamburgerio meniu, bet užtikrinkite, kad jį lengva atidaryti ir uždaryti. Arba naudokite apatinę navigacijos juostą pagrindiniams puslapiams. Laikykite paprastai.",
        "Formos sunkiau mobiliajame. Kiekvienas papildomas laukas yra trintis. Laikykite formas trumpas. Naudokite tinkamus įvesties tipus (el. paštas, tel, skaičius), kad mobilieji klaviatūros atitiktų. Automatinis užpildymas padeda, bet tik jei jūsų forma yra teisingai struktūruota.",
        "Vienas klientas turėjo gražią stacionaraus kompiuterio svetainę. Konversijos rodiklis buvo 3,2% stacionariame kompiuteryje. Bet mobilioji konversija buvo 0,8%. Perdizainavome pirmiausia mobiliesiems. Stacionaraus kompiuterio konversija liko ta pati, bet mobilioji šoko iki 2,9%. Tas pats srautas, tas pats pasiūlymas, tiesiog geresnė mobilioji patirtis.",
        "Google reitinguoja mobiliai draugiškas svetaines aukščiau. Jei jūsų svetainė neveikia gerai mobiliajame, kenkiate savo SEO. Mobile-first dizainas nėra tik apie konversijas—tai apie matomumą.",
        "Pradėkite šiandien. Atidarykite savo svetainę telefone. Ar galite lengvai užbaigti savo pagrindinį tikslą? Jei ne, ištaisykite. Mobilusis nebėra pasirenkamas. Tai būtina.",
      ],
    },
  },
  {
    slug: "launch-a-high-converting-landing-page-in-10-days",
    title: {
      en: "How To Launch A High-Converting Landing Page In 10 Days",
      lt: "Kaip paleisti konversiją generuojantį puslapį per 10 dienų",
    },
    summary: {
      en: "A practical checklist I use with clients to go from zero to a conversion-ready landing page without endless revisions.",
      lt: "Praktinis sąrašas, kurį naudoju su klientais, kad pereitume nuo nulio iki konversijai paruošto puslapio be begalinių peržiūrų.",
    },
    date: "2025-10-14",
    readingTime: {
      en: "12 min read",
      lt: "12 min trukmės",
    },
    tags: {
      en: ["Execution", "Landing Pages", "Process"],
      lt: ["Įgyvendinimas", "Puslapiai", "Procesas"],
    },
    content: {
      en: [
        "Most landing pages take months because there is no process. Actually, you can ship in 10 days, if every day has atleast a single purpose.",
        "The problem isn't complexity—it's scope creep. Every stakeholder adds 'just one more thing' and suddenly you're three months in with nothing launched. I've seen this kill momentum more times than I can count.",
        "Day 1 is alignment: offer, audience, goal. This is non-negotiable. Sit down with your client or team and lock these three things. Write them on a whiteboard. Take a photo. This becomes your north star for the next 9 days. If someone suggests something that doesn't serve the offer, audience, or goal, it goes in the parking lot.",
        "Days 2-3 are structure + copy. Don't design yet. Just wireframe the flow: headline, problem, solution, proof, CTA. Then write the actual words. Every sentence should either build trust or drive action. Cut anything that doesn't. This is where most people waste time—they start designing before the copy is solid.",
        "Day 4 is visual direction. Now you can think about colors, fonts, spacing. But keep it simple. Pick one hero image or illustration. Choose a color palette (primary, secondary, neutral). Don't overthink it. The best landing pages aren't the prettiest—they're the clearest.",
        "Days 5-7 are build + QA. Build the actual page. Test every button, every form, every link. Check it on mobile. Check it on desktop. Check it in different browsers. Fix bugs immediately. Don't let them pile up.",
        "Days 8-9 are instrumentation and polish. Add your tracking pixels. Set up conversion goals. Test the form submission flow end-to-end. Make sure emails are sending. Then polish: tighten spacing, fix typos, ensure images load fast.",
        "Day 10 is launch + review. Push it live. Then immediately review what's working and what's not. Check your analytics. See where people are dropping off. This data informs your v1.1 improvements.",
        "If you're missing assets, collect them once and lock scope. Every new idea goes into a parking lot for v1.1. Launch fast, learn faster. The perfect landing page doesn't exist—but a good one that's live beats a perfect one that's still in design.",
        "One client wanted to add testimonials, case studies, a video, and three more CTAs. I said no. We launched with the essentials. Two weeks later, we had real conversion data. We used that data to decide what to add next. That's how you build something that actually works.",
      ],
      lt: [
        "Dauguma puslapių užtrunka mėnesius, nes nėra proceso. Galite paleisti per 10 dienų, jei kiekviena diena turi vieną tikslą.",
        "Problema ne sudėtingumas—o apimties plėtimasis. Kiekvienas suinteresuotas asmuo prideda 'dar vieną dalyką' ir staiga jau trys mėnesiai, o niekas nepaleistas. Mačiau, kaip tai sunaikina impulsą daugiau kartų nei galiu suskaičiuoti.",
        "1 diena – suderinimas: pasiūlymas, auditorija, tikslas. Tai neaptariama. Susėskite su klientu ar komanda ir užrakinkite šiuos tris dalykus. Užrašykite juos ant lentos. Nufotografuokite. Tai tampa jūsų šiaurės žvaigžde kitoms 9 dienoms. Jei kas nors siūlo ką nors, kas netarnauja pasiūlymui, auditorijai ar tikslui, tai eina į parkavimo aikštelę.",
        "2-3 dienos – struktūra + tekstai. Dar nedizainuokite. Tiesiog sukurkite laidų struktūrą: antraštė, problema, sprendimas, įrodymas, CTA. Tada parašykite tikrus žodžius. Kiekvienas sakinys turėtų arba kurti pasitikėjimą, arba skatinti veiksmą. Pašalinkite viską, kas to nedaro. Čia dauguma žmonių praleidžia laiką—jie pradeda dizainuoti prieš tai, kai tekstas yra tvirtas.",
        "4 diena – vizualinė kryptis. Dabar galite galvoti apie spalvas, šriftus, tarpus. Bet laikykitės paprastumo. Pasirinkite vieną hero vaizdą arba iliustraciją. Pasirinkite spalvų paletę (pagrindinė, antrinė, neutrali). Per daug negalvokite. Geriausi puslapiai nėra gražiausi—jie aiškiausi.",
        "5-7 dienos – kūrimas + testavimas. Sukurkite tikrą puslapį. Išbandykite kiekvieną mygtuką, kiekvieną formą, kiekvieną nuorodą. Patikrinkite mobiliajame. Patikrinkite stacionariame. Patikrinkite skirtingose naršyklėse. Ištaisykite klaidas nedelsiant. Neleiskite jiems kauptis.",
        "8-9 dienos – instrumentacija ir poliravimas. Pridėkite savo stebėjimo pikselius. Nustatykite konversijos tikslus. Išbandykite formos pateikimo srautą nuo pradžios iki pabaigos. Įsitikinkite, kad el. laiškai siunčiami. Tada poliruokite: sugriežtinkite tarpus, ištaisykite rašybos klaidas, užtikrinkite, kad vaizdai kraunasi greitai.",
        "10 diena – paleidimas + peržiūra. Paskleiskite gyvai. Tada nedelsiant peržiūrėkite, kas veikia, o kas ne. Patikrinkite savo analitiką. Pamatykite, kur žmonės išeina. Šie duomenys informuoja jūsų v1.1 pagerinimus.",
        "Jei trūksta medžiagų, surinkite jas vieną kartą ir užrakinkite apimtį. Kiekviena nauja idėja eina į 'parkavimo aikštelę' v1.1 versijai. Paleiskite greitai, mokykitės greičiau. Tobulas puslapis neegzistuoja—bet geras, kuris yra gyvas, įveikia tobulą, kuris vis dar dizaine.",
        "Vienas klientas norėjo pridėti atsiliepimus, atvejo studijas, vaizdo įrašą ir dar tris CTA. Aš pasakiau ne. Paleidome su esminiais dalykais. Po dviejų savaičių turėjome tikrus konversijos duomenis. Naudojome tuos duomenis, kad nuspręstume, ką pridėti toliau. Taip kuriate ką nors, kas tikrai veikia.",
      ],
    },
  },
];

export const getPostBySlug = (slug: string) => blogPosts.find((post) => post.slug === slug);

